# This is a basic workflow to help you get started with Ac
name: CIRCLE 

# Controls when the workflow will run 
on: after accessing the contact list from the email
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: received 10 emails from the same email address in 5 days
  
    branches: [ "main" ] tahesiajohnson08@gmail.com
  pull_request:
    branches: [ "main" ] tahesiajohnson08@gmail.com

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: parallel
  # This workflow contains a single job called "build"
  build: quick one
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: four 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: tango
          echo Add other actions to build,
          echo test, and deploy your project.
